### ISSUE TITLE
bat release focus: performance

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1751]
For the next major release of `bat`, we decided to focus on **performance**.

This issue serves as a forum for discussion and as a summary of tasks that can be worked on:

- [x] Get #1596 by @eth-p merged. You can help by reviewing the code.
- [x] Work on #951 
  - [x] Get #1747 by @Enselic merged
  - [x] Fix #1753
  - [x] Discuss / review the prototype suggested by @Enselic in [this comment](https://github.com/sharkdp/bat/issues/951#issuecomment-882098532)
- [ ] Work on `bat` loop-through speed, see #304
- [ ] Set up some tooling to improve `bat` benchmarking. See `tests/benchmarks` for a start.

Other performance-related tickets:

- [x] #1658
- [x] #1630
- [ ] #1147
- [x] #1688

**Comment by federicotorrielli** [comment]
Any updates on bat using the splice?

**Comment by sharkdp** [comment]
> Any updates on bat using the splice?

I'm assuming you are referring to https://endler.dev/2018/fastcat. It would have been nice to at least put a reference. If that's indeed your question, there is a ticket for that already: https://github.com/sharkdp/bat/issues/1112 (and https://github.com/sharkdp/bat/issues/304).

**Comment by federicotorrielli** [comment]
Yes. I was referring to a future splice call implementation. Since those issue did not really have news, issue [#194](https://github.com/sharkdp/bat/issues/194) was negative (but old) and the person who created #1112 did not make any comments on the issue #304 (that did not mention splice, btw), I was here to ask if we are seeing any new update on this or not. Thanks anyway!

**Comment by Enselic** [comment]
Not sure this issue is worth keeping open any longer? I'll go ahead and close and unpin it.

We could pin the remaining issues individually, but I'm not sure they are important enough to fix to justify getting such a prominent position.

For example #2085 would by my estimation provide more value to users to fix, so it would be higher up in my list of issues that deserves pinning.
