### ISSUE TITLE
Tracking issue for bat v1.0.0

### ISSUE THREAD

**Issue by Enselic** [sharkdp/bat#2221]
At one point it would be nice to release bat v1.0.0.

This issue tracks various initiatives that needs to be taken or that has been taken to reach that goal.

An incomplete list of things to do before before releasing bat v1.0.0:

* [ ] Split out the unstable parts of the `bat` library API into a new crate `bat-impl`. Draft: https://github.com/Enselic/bat/pull/125
* [ ] Go through all (or at least the most used) [crates that depend on bat](https://crates.io/crates/bat/reverse_dependencies) to make sure the bat v1.0.0 API is sufficient. I already looked at the most popular bat dependent, namely cargo-expand, and after https://github.com/dtolnay/cargo-expand/pull/148 that particular crate should have no troubles to upgrade to bat v1.0.0.
* [ ] Clean up the parts of what can become the bat v1.0 API, which will basically be just `bat::PrettyPrinter`, to avoid unwanted things outside of our control. For example, the API to list all syntaxes exposes a `syntect` data structure. We should abstract that away.
* [ ] I think we need to solve https://github.com/sharkdp/bat/issues/2085 to make bat version upgrades smooth. Maybe by having separate versioning of the binary format of assets.
